image: node:10.5.0-alpine
stages:
  - test
  - deploy
before_script:
  - echo 'Using Node.js version' $(node -v)
  - echo 'Using npm version' $(npm -v)

test:
  stage: test
  variables:
    APP_ENV: "test"
    NODE_ENV: "test"
    CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  script:
    - npm ci
    - npm test
    - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage -t $CODACY_PROJECT_TOKEN -v -c $CI_COMMIT_SHA

pages: # the job must be named pages
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv storybook-dist public
  artifacts:
    paths:
      - public
  environment:
      name: production
  only:
    - tags

publish:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish --access public
  only:
    - tags
