image: node:10.5.0-alpine
stages:
  - test
  - deploy
before_script:
  - echo 'Using Node.js version' $(node -v)
  - echo 'Using npm version' $(npm -v)

test:
  stage: test
  variables:
    APP_ENV: "test"
    NODE_ENV: "test"
  script:
    - npm ci
    - npm test

pages: # the job must be named pages
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv storybook-dist public
  artifacts:
    paths:
      - public
  only:
    - tags

publish:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish --access public
  only:
    - tags
