image: node:10.5.0-alpine
stages:
  - deploy

pages: # the job must be named pages
  stage: deploy
  script:
    - npm ci
    - npm run build
    - mv storybook-dist public
  artifacts:
    paths:
      - public
  only:
    - tags

publish:
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    - npm publish --access public
  only:
    - tags
